/**
 * script.js — Portfolio rendering engine.
 * Reads from PORTFOLIO_DATA in data.js and builds the entire UI.
 * Do NOT edit this file to update content — edit data.js instead.
 */

(function () {
    'use strict';

    const D = PORTFOLIO_DATA;

    // ── Helpers ───────────────────────────────────────────────
    const $ = (id) => document.getElementById(id);
    const el = (tag, cls, html) => {
        const e = document.createElement(tag);
        if (cls) e.className = cls;
        if (html !== undefined) e.innerHTML = html;
        return e;
    };

    // Lucide icon helper (inline SVG paths via CDN)
    const ICONS = {
        'train-front': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect x="4" y="3" width="16" height="16" rx="2"/><path d="M4 11h16"/><path d="M12 3v8"/><path d="m8 19-2 3"/><path d="m18 22-2-3"/><path d="M8 15h.01M16 15h.01"/></svg>',
        'leaf': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M11 20A7 7 0 0 1 9.8 6.1C15.5 5 17 4.48 19 2c1 2 2 4.18 2 8 0 5.5-4.78 10-10 10z"/><path d="M2 21c0-3 1.85-5.36 5.08-6C9.5 14.52 12 13 13 12"/></svg>',
        'library': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m16 6 4 14"/><path d="M12 6v14"/><path d="M8 8v12"/><path d="M4 4v16"/></svg>',
        'bot': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 8V4H8"/><rect width="16" height="12" x="4" y="8" rx="2"/><path d="M2 14h2"/><path d="M20 14h2"/><path d="M15 13v2"/><path d="M9 13v2"/></svg>',
        'shopping-cart': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><circle cx="8" cy="21" r="1"/><circle cx="19" cy="21" r="1"/><path d="M2.05 2.05h2l2.66 12.42a2 2 0 0 0 2 1.58h9.78a2 2 0 0 0 1.95-1.57l1.65-7.43H5.12"/></svg>',
        'mic': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M12 2a3 3 0 0 0-3 3v7a3 3 0 0 0 6 0V5a3 3 0 0 0-3-3Z"/><path d="M19 10v2a7 7 0 0 1-14 0v-2"/><line x1="12" x2="12" y1="19" y2="22"/></svg>',
        'music': '<svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M9 18V5l12-2v13"/><circle cx="6" cy="18" r="3"/><circle cx="18" cy="16" r="3"/></svg>',
        'code': '<svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="16 18 22 12 16 6"/><polyline points="8 6 2 12 8 18"/></svg>',
        'play': '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polygon points="5 3 19 12 5 21 5 3"/></svg>',
        'external-link': '<svg xmlns="http://www.w3.org/2000/svg" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M18 13v6a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V8a2 2 0 0 1 2-2h6"/><polyline points="15 3 21 3 21 9"/><line x1="10" y1="14" x2="21" y2="3"/></svg>',
        'mail': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><rect width="20" height="16" x="2" y="4" rx="2"/><path d="m22 7-8.97 5.7a1.94 1.94 0 0 1-2.06 0L2 7"/></svg>',
        'phone': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 16.92v3a2 2 0 0 1-2.18 2 19.79 19.79 0 0 1-8.63-3.07A19.5 19.5 0 0 1 4.69 12 19.79 19.79 0 0 1 1.61 3.44 2 2 0 0 1 3.6 1.27h3a2 2 0 0 1 2 1.72 12.84 12.84 0 0 0 .7 2.81 2 2 0 0 1-.45 2.11L7.91 9a16 16 0 0 0 6 6l1.9-1.9a2 2 0 0 1 2.11-.45 12.84 12.84 0 0 0 2.81.7A2 2 0 0 1 22 16.92z"/></svg>',
        'linkedin': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M16 8a6 6 0 0 1 6 6v7h-4v-7a2 2 0 0 0-2-2 2 2 0 0 0-2 2v7h-4v-7a6 6 0 0 1 6-6z"/><rect width="4" height="12" x="2" y="9"/><circle cx="4" cy="4" r="2"/></svg>',
        'map-pin': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M20 10c0 6-8 12-8 12s-8-6-8-12a8 8 0 0 1 16 0Z"/><circle cx="12" cy="10" r="3"/></svg>',
        'download': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4"/><polyline points="7 10 12 15 17 10"/><line x1="12" y1="15" x2="12" y2="3"/></svg>',
        'arrow-right': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M5 12h14"/><path d="m12 5 7 7-7 7"/></svg>',
        'graduation-cap': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M22 10v6M2 10l10-5 10 5-10 5z"/><path d="M6 12v5c0 2 2 3 6 3s6-1 6-3v-5"/></svg>',
        'code-2': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="m18 16 4-4-4-4"/><path d="m6 8-4 4 4 4"/><path d="m14.5 4-5 16"/></svg>',
        'wrench': '<svg xmlns="http://www.w3.org/2000/svg" width="18" height="18" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><path d="M14.7 6.3a1 1 0 0 0 0 1.4l1.6 1.6a1 1 0 0 0 1.4 0l3.77-3.77a6 6 0 0 1-7.94 7.94l-6.91 6.91a2.12 2.12 0 0 1-3-3l6.91-6.91a6 6 0 0 1 7.94-7.94l-3.76 3.76z"/></svg>'
    };

    function icon(name) {
        return ICONS[name] || `<svg width="18" height="18" viewBox="0 0 24 24"><circle cx="12" cy="12" r="10" stroke="currentColor" stroke-width="2" fill="none"/></svg>`;
    }

    // ── 1. Navigation ─────────────────────────────────────
    function buildNav() {
        $('nav-logo').innerHTML = `${D.personal.initials}<span>.</span>`;
        const sections = ['home', 'about', 'experience', 'projects', 'contact'];
        const labels   = ['Home', 'About', 'Experience', 'Projects', 'Contact'];
        $('nav-links').innerHTML = sections.map((s, i) =>
            `<li><a href="#${s}">${labels[i]}</a></li>`
        ).join('');

        // Mobile toggle
        $('mobile-menu-btn').addEventListener('click', () => {
            $('nav-links').classList.toggle('mobile-open');
        });
    }

    // ── 2. Hero ───────────────────────────────────────────
    function buildHero() {
        const p = D.personal;
        $('hero-name').textContent = p.name;
        $('hero-name').dataset.text = p.name;
        $('hero-tagline').textContent = p.tagline;
        if (p.image) $('profile-img').src = p.image;

        $('hero-cta').innerHTML = `
            <a href="#projects" class="btn btn-primary">
                <span>View My Work</span>${icon('arrow-right')}
            </a>
            <a href="${encodeURI(p.cvFile)}" target="_blank" class="btn btn-glass">
                ${icon('download')}<span>Download CV</span>
            </a>`;

        // Typewriter
        const roles = p.roles;
        let rIdx = 0, cIdx = 0, deleting = false;
        const tw = $('typewriter');

        (function type() {
            const cur = roles[rIdx];
            if (deleting) {
                tw.textContent = cur.substring(0, --cIdx);
                if (cIdx === 0) { deleting = false; rIdx = (rIdx + 1) % roles.length; }
                setTimeout(type, deleting ? 50 : 500);
            } else {
                tw.textContent = cur.substring(0, ++cIdx);
                if (cIdx === cur.length) { deleting = true; setTimeout(type, 2200); return; }
                setTimeout(type, 100);
            }
        })();
    }

    // ── 3. Education & Skills ─────────────────────────────
    function buildAbout() {
        // Education
        const edu = $('education-list');
        edu.innerHTML = `<h3>${icon('graduation-cap')} Education</h3>`;
        D.education.forEach(e => {
            const d = el('div', 'edu-item');
            d.innerHTML = `<h4>${e.degree}</h4><p class="inst">${e.institution}</p><p class="year">${e.period}</p>`;
            edu.appendChild(d);
        });

        // Skills
        const sk = $('skills-container');
        sk.innerHTML = `
            <h3>${icon('code-2')} Technical Skills</h3>
            <div class="skills-grid">${D.technicalSkills.map(s => `<div class="skill-tag">${s}</div>`).join('')}</div>
            <h3 class="mt-4">${icon('wrench')} Tools & IDEs</h3>
            <div class="skills-grid">${D.tools.map(s => `<div class="skill-tag outline">${s}</div>`).join('')}</div>
        `;
    }

    // ── 4. Experience Timeline ────────────────────────────
    function buildExperience() {
        const tl = $('timeline');
        tl.innerHTML = D.experience.map(e => `
            <div class="timeline-item">
                <div class="timeline-dot"></div>
                <div class="timeline-content glass-card">
                    <span class="date">${e.period}</span>
                    <h3>${e.title}</h3>
                    <h4>${e.company}</h4>
                </div>
            </div>`).join('');
    }

    // ── 5. Projects ───────────────────────────────────────
    function buildProjects() {
        // Collect unique tags for filter buttons
        const allTags = [...new Set(D.projects.flatMap(p => p.tags))];
        const filters = $('project-filters');
        filters.innerHTML = `<button class="filter-btn active" data-tag="all">All</button>`
            + allTags.map(t => `<button class="filter-btn" data-tag="${t}">${t}</button>`).join('');

        // Render cards
        renderProjectCards('all');

        // Filter click
        filters.addEventListener('click', e => {
            const btn = e.target.closest('.filter-btn');
            if (!btn) return;
            filters.querySelectorAll('.filter-btn').forEach(b => b.classList.remove('active'));
            btn.classList.add('active');
            renderProjectCards(btn.dataset.tag);
        });
    }

    function renderProjectCards(activeTag) {
        const grid = $('projects-grid');
        const list = activeTag === 'all'
            ? D.projects
            : D.projects.filter(p => p.tags.includes(activeTag));

        grid.innerHTML = list.map(p => {
            const sourceBtn = p.sourceFile
                ? `<a href="${p.sourceFile}" class="btn-source" target="_blank" title="View Source">${icon('code')} Source</a>`
                : '';

            const demoBtn = p.demoType !== 'none'
                ? `<button class="btn-demo" onclick="window.openDemo('${p.id}')" title="Live Demo">${icon('play')} Live Demo</button>`
                : '';

            const liveBtn = p.liveUrl
                ? `<a href="${p.liveUrl}" class="btn-source btn-live" target="_blank" title="Open App">${icon('external-link')} Open App</a>`
                : '';

            return `
            <div class="project-card glass-card" data-tags="${p.tags.join(',')}">
                <div class="project-icon">${icon(p.icon)}</div>
                <h3>${p.title}</h3>
                <p>${p.description}</p>
                <div class="tech-stack">${p.tags.map(t => `<span>${t}</span>`).join('')}</div>
                <div class="project-links">
                    <div class="project-links-left">${sourceBtn}${liveBtn}</div>
                    ${demoBtn}
                </div>
            </div>`;
        }).join('');
    }

    // ── 6. Extracurricular Activities ───────────────────────
    function buildActivities() {
        const grid = $('activities-grid');
        grid.innerHTML = D.activities.map(act => `
            <div class="activity-card glass-card">
                <div class="activity-icon">${icon('graduation-cap')}</div>
                <div class="activity-text">${act}</div>
            </div>
        `).join('');
    }

    // ── 7. Contact ────────────────────────────────────────
    function buildContact() {
        const p = D.personal;
        const links = [
            { href: `mailto:${p.email}`,  ico: 'mail',     label: p.email },
            { href: `tel:${p.phone.split('/')[0].trim()}`, ico: 'phone', label: p.phone },
            { href: p.linkedin,            ico: 'linkedin', label: 'LinkedIn Profile', blank: true },
            { href: null,                  ico: 'map-pin',  label: p.location }
        ];

        $('contact-links').innerHTML = links.map(l => {
            const tag = l.href ? 'a' : 'div';
            const attrs = l.href ? `href="${l.href}"${l.blank ? ' target="_blank"' : ''}` : '';
            return `<${tag} ${attrs} class="contact-link">
                <div class="icon-wrap">${icon(l.ico)}</div>
                <span>${l.label}</span>
            </${tag}>`;
        }).join('');
    }

    // ── 8. Footer ─────────────────────────────────────────
    function buildFooter() {
        $('footer-text').innerHTML = `&copy; ${new Date().getFullYear()} ${D.personal.name}. Crafted with precision.`;
    }

    // ── 9. Demo Terminal Modal ────────────────────────────
    let demoTimer = null;

    window.openDemo = function (projectId) {
        const project = D.projects.find(p => p.id === projectId);
        if (!project) return;

        const modal = $('demo-modal');
        const body  = $('terminal-body');
        $('demo-modal-title').textContent = `${project.title} — Demo`;

        modal.style.display = 'flex';
        body.innerHTML = '';

        clearTimeout(demoTimer);
        let i = 0;

        function next() {
            if (i >= project.demo.length) return;
            const item = project.demo[i++];
            const div = el('div', `tline ${item.type}`);

            if (item.type === 'command') {
                div.innerHTML = `<span class="prompt">tharindu@pc:~$</span>&nbsp;${item.text}`;
            } else if (item.type === 'input') {
                div.innerHTML = `<span class="prompt-in">&gt;&gt;</span>&nbsp;${item.text}`;
            } else {
                div.textContent = item.text;
            }

            body.appendChild(div);
            body.scrollTop = body.scrollHeight;

            const delay = item.type === 'command' ? 900 : item.type === 'input' ? 700 : 480;
            demoTimer = setTimeout(next, delay);
        }
        next();
    };

    function closeDemo() {
        $('demo-modal').style.display = 'none';
        clearTimeout(demoTimer);
    }

    // ── 10. Scroll Effects ─────────────────────────────────
    function initScrollEffects() {
        const obs = new IntersectionObserver((entries) => {
            entries.forEach(e => { if (e.isIntersecting) { e.target.classList.add('visible'); obs.unobserve(e.target); } });
        }, { threshold: 0.12 });
        document.querySelectorAll('.fade-in').forEach(el => obs.observe(el));

        // Active nav highlight
        const sections = document.querySelectorAll('section');
        window.addEventListener('scroll', () => {
            const scrollY = window.pageYOffset;
            let current = '';
            sections.forEach(s => { if (scrollY >= s.offsetTop - 120) current = s.id; });
            document.querySelectorAll('.nav-links a').forEach(a => {
                a.classList.toggle('active', a.getAttribute('href') === `#${current}`);
            });
            // Nav blur
            const nav = document.querySelector('.glass-nav');
            nav.style.background = scrollY > 50 ? 'rgba(5,5,5,0.9)' : 'rgba(5,5,5,0.7)';
        }, { passive: true });
    }

    // ── 11. Modal wiring ──────────────────────────────────
    function initModal() {
        $('modal-close-btn').addEventListener('click', closeDemo);
        $('modal-close-dot').addEventListener('click', closeDemo);
        $('modal-close-dot').addEventListener('keydown', e => { if (e.key === 'Enter') closeDemo(); });
        $('demo-modal').addEventListener('click', e => { if (e.target === $('demo-modal')) closeDemo(); });
        document.addEventListener('keydown', e => { if (e.key === 'Escape') closeDemo(); });
    }

    // ── 12. Orb mouse parallax ────────────────────────────
    function initOrbs() {
        const orbs = document.querySelectorAll('.orb');
        document.addEventListener('mousemove', (e) => {
            const x = e.clientX / window.innerWidth;
            const y = e.clientY / window.innerHeight;
            orbs.forEach((orb, i) => {
                const f = (i + 1) * 25;
                orb.style.transform = `translate(${x * f}px, ${y * f}px)`;
            });
        }, { passive: true });
    }

    // ── 13. Contact Form & Admin Logic ────────────────────
    function initContactForm() {
        const form = $('contact-form');
        if (!form) return;

        // WhatsApp Click
        $('btn-whatsapp').addEventListener('click', () => {
            const name = $('c-name').value;
            const msg  = $('c-message').value;
            if (!name || !msg) return alert('Please enter your name and message first.');
            
            const phone = D.personal.phone.replace(/\D/g, ''); // Extract only digits
            const text = encodeURIComponent(`Hello Tharindu!\n\nName: ${name}\nMessage: ${msg}`);
            window.open(`https://wa.me/${phone}?text=${text}`, '_blank');
        });

        // Email Submission (via Formspree)
        form.addEventListener('submit', (e) => {
            e.preventDefault();
            const btn = $('btn-email');
            const originalText = btn.innerHTML;
            
            btn.innerHTML = '<span>Sending...</span>';
            btn.disabled = true;

            // Formspree Integration
            const formData = {
                name: $('c-name').value,
                email: $('c-email').value,
                message: $('c-message').value
            };

            fetch('https://formspree.io/f/xvgozvww', { // Default Formspree ID (user should replace)
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(formData)
            })
            .then(() => {
                btn.innerHTML = '<span>Success!</span>';
                form.reset();
                setTimeout(() => {
                    btn.innerHTML = originalText;
                    btn.disabled = false;
                }, 3000);
            })
            .catch(() => {
                alert('Email service error. Try WhatsApp instead!');
                btn.innerHTML = originalText;
                btn.disabled = false;
            });
        });
    }

    // ── 14. Admin Mode (The Management Tool) ─────────────
    function initAdminMode() {
        const trigger = $('admin-trigger');
        const modal   = $('admin-modal');
        const close   = $('admin-close-btn');
        let localData = JSON.parse(JSON.stringify(D));

        trigger.addEventListener('click', () => {
            modal.style.display = 'flex';
            renderTab('personal-tab');
        });

        close.addEventListener('click', () => modal.style.display = 'none');

        // Tab Logic
        document.querySelectorAll('.tab-btn').forEach(btn => {
            btn.addEventListener('click', () => {
                document.querySelectorAll('.tab-btn, .tab-content').forEach(el => el.classList.remove('active'));
                btn.classList.add('active');
                $(btn.dataset.tab).classList.add('active');
                renderTab(btn.dataset.tab);
            });
        });

        function renderTab(tabId) {
            if (tabId === 'personal-tab') renderPersonal();
            if (tabId === 'projects-tab') renderProjects();
            if (tabId === 'export-tab') updateExportCode();
        }

        // Global Update Helper
        window.updateField = (path, value) => {
            const keys = path.split('.');
            let obj = localData;
            for (let i = 0; i < keys.length - 1; i++) obj = obj[keys[i]];
            obj[keys[keys.length - 1]] = value;
            updateExportCode();
        };

        function renderPersonal() {
            const p = localData.personal;
            $('personal-tab').innerHTML = `
                <div class="admin-form">
                    <h3>Personal Information</h3>
                    <div class="admin-form-row">
                        <div class="admin-form-group"><label>Full Name</label><input type="text" value="${p.name}" oninput="updateField('personal.name', this.value)"></div>
                        <div class="admin-form-group"><label>Tagline</label><input type="text" value="${p.tagline}" oninput="updateField('personal.tagline', this.value)"></div>
                    </div>
                    <div class="admin-form-row">
                        <div class="admin-form-group"><label>Profile Image URL</label><input type="text" value="${p.image || ''}" oninput="updateField('personal.image', this.value); document.getElementById('profile-img').src=this.value"></div>
                        <div class="admin-form-group"><label>Location</label><input type="text" value="${p.location}" oninput="updateField('personal.location', this.value)"></div>
                    </div>
                    <div class="admin-form-row">
                        <div class="admin-form-group"><label>Email</label><input type="text" value="${p.email}" oninput="updateField('personal.email', this.value)"></div>
                        <div class="admin-form-group"><label>Phone</label><input type="text" value="${p.phone}" oninput="updateField('personal.phone', this.value)"></div>
                    </div>
                    
                    <h3 class="mt-4">Education</h3>
                    ${localData.education.map((e, i) => `
                        <div class="admin-form-row" style="background:rgba(255,255,255,0.02); padding:10px; border-radius:8px; margin-bottom:10px;">
                            <div class="admin-form-group"><label>Degree</label><input type="text" value="${e.degree}" oninput="updateField('education.${i}.degree', this.value)"></div>
                            <div class="admin-form-group"><label>Period/Date</label><input type="text" value="${e.period}" oninput="updateField('education.${i}.period', this.value)"></div>
                        </div>
                    `).join('')}
                </div>
            `;
        }

        function renderProjects() {
            const list = $('admin-project-list');
            list.innerHTML = localData.projects.map((p, idx) => `
                <div class="admin-project-item" style="flex-direction:column; align-items:flex-start; gap:10px;">
                    <div style="display:flex; justify-content:space-between; width:100%;">
                        <h4>${p.title}</h4>
                        <button class="btn-demo" style="background:#ff5f56; padding:4px 10px;" onclick="removeProject(${idx})">Delete</button>
                    </div>
                    <div class="admin-form-row" style="width:100%;">
                        <div class="admin-form-group"><label>Title</label><input type="text" value="${p.title}" oninput="updateField('projects.${idx}.title', this.value)"></div>
                        <div class="admin-form-group"><label>Description</label><input type="text" value="${p.description}" oninput="updateField('projects.${idx}.description', this.value)"></div>
                    </div>
                </div>
            `).join('');
        }

        window.removeProject = (idx) => {
            localData.projects.splice(idx, 1);
            renderProjects();
            updateExportCode();
        };

        $('btn-add-project').addEventListener('click', () => {
            localData.projects.push({
                id: "new-proj-" + Date.now(),
                icon: "code",
                title: "New Project",
                description: "Description here...",
                tags: ["Java"],
                sourceFile: "",
                demoType: "none",
                demo: []
            });
            renderProjects();
            updateExportCode();
        });

        function updateExportCode() {
            const code = `const PORTFOLIO_DATA = ${JSON.stringify(localData, null, 4)};`;
            $('code-export-pre').textContent = code;
        }

        $('btn-copy-code').addEventListener('click', () => {
            navigator.clipboard.writeText($('code-export-pre').textContent);
            const btn = $('btn-copy-code');
            btn.textContent = '✅ Copied!';
            setTimeout(() => btn.textContent = 'Copy Code', 2000);
        });

        const downloadBtn = $('btn-download-data');
        if (downloadBtn) {
            downloadBtn.addEventListener('click', () => {
                const code = $('code-export-pre').textContent;
                const blob = new Blob([code], { type: 'text/javascript' });
                const url = URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.href = url;
                a.download = 'data.js';
                a.click();
                URL.revokeObjectURL(url);
            });
        }

        // Add a "Apply & Close" button to the modal
        const applyBtn = document.createElement('button');
        applyBtn.className = 'btn btn-primary mt-4';
        applyBtn.style.width = '100%';
        applyBtn.textContent = 'Apply Changes Temporarily (Live Preview)';
        applyBtn.onclick = () => {
            // Hot-swap the live data without reloading!
            Object.assign(D, localData);
            
            // Re-render the UI dynamically
            buildNav();
            buildHero();
            buildAbout();
            buildExperience();
            buildProjects();
            buildActivities();
            buildContact();
            buildFooter();
            
            modal.style.display = 'none';
        };
        $('export-tab').appendChild(applyBtn);
    }

    // ── BOOT ──────────────────────────────────────────────
    document.addEventListener('DOMContentLoaded', () => {
        buildNav();
        buildHero();
        buildAbout();
        buildExperience();
        buildProjects();
        buildActivities();
        buildContact();
        buildFooter();
        initScrollEffects();
        initModal();
        initOrbs();
        initContactForm();
        initAdminMode();
    });

})();
